import { Arbol, Producto } from '~/store/Arbol'

let gData = () => {
  //se crea el arbol
  let t = new Arbol()
  //se agrega el nodo principal
  t.agregarNodo('Abarrofarmacia')
  //se agrega el nodo de san marcos
  t.agregarNodo('Dep San Marcos', 'Abarrofarmacia')
  //se agrega el nodo se malacatan
  t.agregarNodo('Malacatan', 'Dep San Marcos')
  t.agregarNodo('San Pablo', 'Dep San Marcos')
  t.agregarNodo('Catarina', 'Dep San Marcos')
  t.agregarNodo('Tecun Uman', 'Dep San Marcos')
  t.agregarNodo('San Rafael', 'Dep San Marcos')
  t.agregarNodo('San Marcos', 'Dep San Marcos')

  //Productos de Malacatan
  t.agregarNodo(new Producto('azucar', '5', 0), 'Malacatan')
  t.agregarNodo(new Producto('leche', '12', 0), 'Malacatan')
  t.agregarNodo(new Producto('papel', '12', 0), 'Malacatan')
  t.agregarNodo(new Producto('aceite', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('aderezos', '12', 0), 'Malacatan')
  t.agregarNodo(new Producto('cafe', '5', 0), 'Malacatan')
  t.agregarNodo(new Producto('avena', '7', 0), 'Malacatan')
  t.agregarNodo(new Producto('cereales', '25', '10'), 'Malacatan')
  t.agregarNodo(new Producto('sal', '3', '10'), 'Malacatan')
  t.agregarNodo(new Producto('miel', '20', '10'), 'Malacatan')
  t.agregarNodo(new Producto('mayonesa', '15', '10'), 'Malacatan')
  t.agregarNodo(new Producto('mermelada', '12', '10'), 'Malacatan')
  t.agregarNodo(new Producto('te', '6', '10'), 'Malacatan')
  t.agregarNodo(new Producto('vinagre', '10', '10'), 'Malacatan')
  t.agregarNodo(new Producto('huevos', '25', '10'), 'Malacatan')
  t.agregarNodo(new Producto('pastas', '3', '10'), 'Malacatan')
  t.agregarNodo(new Producto('aceitunas', '8', '10'), 'Malacatan')
  t.agregarNodo(new Producto('champinones', '10', '10'), 'Malacatan')
  t.agregarNodo(new Producto('frijoles', '9', '10'), 'Malacatan')
  t.agregarNodo(new Producto('sardina', '7', '10'), 'Malacatan')
  t.agregarNodo(new Producto('atun', '15', 10), 'Malacatan')
  t.agregarNodo(new Producto('chile enlatado', '5', '10'), 'Malacatan')
  t.agregarNodo(new Producto('ensalada enlatada', '20', '10'), 'Malacatan')
  t.agregarNodo(new Producto('elote enlatado', '12', '10'), 'Malacatan')
  t.agregarNodo(new Producto('sopa enlatada', '5', 0), 'Malacatan')
  t.agregarNodo(new Producto('fruta enlatada', '25', 0), 'Malacatan')
  t.agregarNodo(new Producto('crema', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('margarina', '7', 0), 'Malacatan')
  t.agregarNodo(new Producto('queso', '20', 0), 'Malacatan')
  t.agregarNodo(new Producto('papa', '5', 0), 'Malacatan')
  t.agregarNodo(new Producto('cacahuates', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('nueces', '15', 0), 'Malacatan')
  t.agregarNodo(new Producto('tortilla de harina', '20', '10'), 'Malacatan')
  t.agregarNodo(new Producto('pan dulce', '2', 0), 'Malacatan')
  t.agregarNodo(new Producto('aguacate', '3', 0), 'Malacatan')
  t.agregarNodo(new Producto('ajo', '4', 10), 'Malacatan')
  t.agregarNodo(new Producto('cebolla', '6', 0), 'Malacatan')
  t.agregarNodo(new Producto('cilantro', '2', 0), 'Malacatan')
  t.agregarNodo(new Producto('tomate', '4', 0), 'Malacatan')
  t.agregarNodo(new Producto('limon', '8', 0), 'Malacatan')
  t.agregarNodo(new Producto('manzana', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('naranja', '12', 0), 'Malacatan')
  t.agregarNodo(new Producto('salchica', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('tocino', '20', 0), 'Malacatan')
  t.agregarNodo(new Producto('jamon', '5', 0), 'Malacatan')
  t.agregarNodo(new Producto('chorizo', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('suero', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('pasta dental', '10', 0), 'Malacatan')
  t.agregarNodo(new Producto('shampoo', '40', 10), 'Malacatan')
  t.agregarNodo(new Producto('servilletas', '5', 5), 'Malacatan')
  t.agregarNodo(new Producto('cloro', '20', 0), 'Malacatan')
  t.agregarNodo(new Producto('desinfectante', '15', 10), 'Malacatan')
  //Productos de San Pablo
  t.agregarNodo(new Producto('azucar', '5', '10'), 'San Pablo')
  t.agregarNodo(new Producto('leche', '12', '10'), 'San Pablo')
  t.agregarNodo(new Producto('papel', '12', '10'), 'San Pablo')
  t.agregarNodo(new Producto('aceite', '10', '10'), 'San Pablo')
  t.agregarNodo(new Producto('aderezos', '12', '10'), 'San Pablo')
  t.agregarNodo(new Producto('cafe', '5', '10'), 'San Pablo')
  t.agregarNodo(new Producto('avena', '7', '10'), 'San Pablo')
  t.agregarNodo(new Producto('cereales', '25', '10'), 'San Pablo')
  t.agregarNodo(new Producto('sal', '3', '10'), 'San Pablo')
  t.agregarNodo(new Producto('miel', '20', '10'), 'San Pablo')
  t.agregarNodo(new Producto('mayonesa', '15', '10'), 'San Pablo')
  t.agregarNodo(new Producto('mermelada', '12', '10'), 'San Pablo')
  t.agregarNodo(new Producto('te', '6', '10'), 'San Pablo')
  t.agregarNodo(new Producto('vinagre', '10', '10'), 'San Pablo')
  t.agregarNodo(new Producto('huevos', '25', '10'), 'San Pablo')
  t.agregarNodo(new Producto('pastas', '3', '10'), 'San Pablo')
  t.agregarNodo(new Producto('aceitunas', '8', '10'), 'San Pablo')
  t.agregarNodo(new Producto('champinones', '10', '10'), 'San Pablo')
  t.agregarNodo(new Producto('frijoles', '9', '10'), 'San Pablo')
  t.agregarNodo(new Producto('sardina', '7', '10'), 'San Pablo')
  t.agregarNodo(new Producto('atun', '15'), 'San Pablo')
  t.agregarNodo(new Producto('chile enlatado', '5', '10'), 'San Pablo')
  t.agregarNodo(new Producto('ensalada enlatada', '20', '10'), 'San Pablo')
  t.agregarNodo(new Producto('elote enlatado', '12', '10'), 'San Pablo')
  t.agregarNodo(new Producto('sopa enlatada', '5'), 'San Pablo')
  t.agregarNodo(new Producto('fruta enlatada', '25'), 'San Pablo')
  t.agregarNodo(new Producto('crema', '10'), 'San Pablo')
  t.agregarNodo(new Producto('margarina', '7'), 'San Pablo')
  t.agregarNodo(new Producto('queso', '20'), 'San Pablo')
  t.agregarNodo(new Producto('papa', '5'), 'San Pablo')
  t.agregarNodo(new Producto('cacahuates', '10'), 'San Pablo')
  t.agregarNodo(new Producto('nueces', '15'), 'San Pablo')
  t.agregarNodo(new Producto('tortilla de harina', '20', '10'), 'San Pablo')
  t.agregarNodo(new Producto('pan dulce', '2'), 'San Pablo')
  t.agregarNodo(new Producto('aguacate', '3'), 'San Pablo')
  t.agregarNodo(new Producto('ajo', '4'), 'San Pablo')
  t.agregarNodo(new Producto('cebolla', '6'), 'San Pablo')
  t.agregarNodo(new Producto('cilantro', '2'), 'San Pablo')
  t.agregarNodo(new Producto('tomate', '4'), 'San Pablo')
  t.agregarNodo(new Producto('limon', '8'), 'San Pablo')
  t.agregarNodo(new Producto('manzana', '10'), 'San Pablo')
  t.agregarNodo(new Producto('naranja', '12'), 'San Pablo')
  t.agregarNodo(new Producto('salchica', '10'), 'San Pablo')
  t.agregarNodo(new Producto('tocino', '20'), 'San Pablo')
  t.agregarNodo(new Producto('jamon', '5'), 'San Pablo')
  t.agregarNodo(new Producto('chorizo', '10'), 'San Pablo')
  t.agregarNodo(new Producto('suero', '10'), 'San Pablo')
  t.agregarNodo(new Producto('pasta dental', '10'), 'San Pablo')
  t.agregarNodo(new Producto('shampoo', '40'), 'San Pablo')
  t.agregarNodo(new Producto('servilletas', '5'), 'San Pablo')
  t.agregarNodo(new Producto('cloro', '20', 0), 'San Pablo')
  t.agregarNodo(new Producto('desinfectante', '15'), 'San Pablo')
  //Productos Catarina
  t.agregarNodo(new Producto('azucar', '5', '10'), 'Catarina')
  t.agregarNodo(new Producto('leche', '12', '10'), 'Catarina')
  t.agregarNodo(new Producto('papel', '12', '10'), 'Catarina')
  t.agregarNodo(new Producto('aceite', '10', '10'), 'Catarina')
  t.agregarNodo(new Producto('aderezos', '12', '10'), 'Catarina')
  t.agregarNodo(new Producto('cafe', '5', '10'), 'Catarina')
  t.agregarNodo(new Producto('avena', '7', '10'), 'Catarina')
  t.agregarNodo(new Producto('cereales', '25', '10'), 'Catarina')
  t.agregarNodo(new Producto('sal', '3', '10'), 'Catarina')
  t.agregarNodo(new Producto('miel', '20', '10'), 'Catarina')
  t.agregarNodo(new Producto('mayonesa', '15', '10'), 'Catarina')
  t.agregarNodo(new Producto('mermelada', '12', '10'), 'Catarina')
  t.agregarNodo(new Producto('te', '6', '10'), 'Catarina')
  t.agregarNodo(new Producto('vinagre', '10', '10'), 'Catarina')
  t.agregarNodo(new Producto('huevos', '25', '10'), 'Catarina')
  t.agregarNodo(new Producto('pastas', '3', '10'), 'Catarina')
  t.agregarNodo(new Producto('aceitunas', '8', '10'), 'Catarina')
  t.agregarNodo(new Producto('champinones', '10', '10'), 'Catarina')
  t.agregarNodo(new Producto('frijoles', '9', '10'), 'Catarina')
  t.agregarNodo(new Producto('sardina', '7', '10'), 'Catarina')
  t.agregarNodo(new Producto('atun', '15'), 'Catarina')
  t.agregarNodo(new Producto('chile enlatado', '5', '10'), 'Catarina')
  t.agregarNodo(new Producto('ensalada enlatada', '20', '10'), 'Catarina')
  t.agregarNodo(new Producto('elote enlatado', '12', '10'), 'Catarina')
  t.agregarNodo(new Producto('sopa enlatada', '5'), 'Catarina')
  t.agregarNodo(new Producto('fruta enlatada', '25'), 'Catarina')
  t.agregarNodo(new Producto('crema', '10'), 'Catarina')
  t.agregarNodo(new Producto('margarina', '7'), 'Catarina')
  t.agregarNodo(new Producto('queso', '20'), 'Catarina')
  t.agregarNodo(new Producto('papa', '5'), 'Catarina')
  t.agregarNodo(new Producto('cacahuates', '10'), 'Catarina')
  t.agregarNodo(new Producto('nueces', '15'), 'Catarina')
  t.agregarNodo(new Producto('tortilla de harina', '20', '10'), 'Catarina')
  t.agregarNodo(new Producto('pan dulce', '2'), 'Catarina')
  t.agregarNodo(new Producto('aguacate', '3'), 'Catarina')
  t.agregarNodo(new Producto('ajo', '4'), 'Catarina')
  t.agregarNodo(new Producto('cebolla', '6'), 'Catarina')
  t.agregarNodo(new Producto('cilantro', '2'), 'Catarina')
  t.agregarNodo(new Producto('tomate', '4'), 'Catarina')
  t.agregarNodo(new Producto('limon', '8'), 'Catarina')
  t.agregarNodo(new Producto('manzana', '10'), 'Catarina')
  t.agregarNodo(new Producto('naranja', '12'), 'Catarina')
  t.agregarNodo(new Producto('salchica', '10'), 'Catarina')
  t.agregarNodo(new Producto('tocino', '20'), 'Catarina')
  t.agregarNodo(new Producto('jamon', '5'), 'Catarina')
  t.agregarNodo(new Producto('chorizo', '10'), 'Catarina')
  t.agregarNodo(new Producto('suero', '10'), 'Catarina')
  t.agregarNodo(new Producto('pasta dental', '10'), 'Catarina')
  t.agregarNodo(new Producto('shampoo', '40'), 'Catarina')
  t.agregarNodo(new Producto('servilletas', '5'), 'Catarina')
  t.agregarNodo(new Producto('cloro', '20', 0), 'Catarina')
  t.agregarNodo(new Producto('desinfectante', '15'), 'Catarina')
  //Productos Tecun Uman
  t.agregarNodo(new Producto('azucar', '5', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('leche', '12', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('papel', '12', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('aceite', '10', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('aderezos', '12', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('cafe', '5', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('avena', '7', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('cereales', '25', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('sal', '3', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('miel', '20', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('mayonesa', '15', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('mermelada', '12', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('te', '6', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('vinagre', '10', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('huevos', '25', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('pastas', '3', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('aceitunas', '8', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('champinones', '10', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('frijoles', '9', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('sardina', '7', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('atun', '15'), 'Tecun Uman')
  t.agregarNodo(new Producto('chile enlatado', '5', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('ensalada enlatada', '20', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('elote enlatado', '12', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('sopa enlatada', '5'), 'Tecun Uman')
  t.agregarNodo(new Producto('fruta enlatada', '25'), 'Tecun Uman')
  t.agregarNodo(new Producto('crema', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('margarina', '7'), 'Tecun Uman')
  t.agregarNodo(new Producto('queso', '20'), 'Tecun Uman')
  t.agregarNodo(new Producto('papa', '5'), 'Tecun Uman')
  t.agregarNodo(new Producto('cacahuates', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('nueces', '15'), 'Tecun Uman')
  t.agregarNodo(new Producto('tortilla de harina', '20', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('pan dulce', '2'), 'Tecun Uman')
  t.agregarNodo(new Producto('aguacate', '3'), 'Tecun Uman')
  t.agregarNodo(new Producto('ajo', '4'), 'Tecun Uman')
  t.agregarNodo(new Producto('cebolla', '6'), 'Tecun Uman')
  t.agregarNodo(new Producto('cilantro', '2'), 'Tecun Uman')
  t.agregarNodo(new Producto('tomate', '4'), 'Tecun Uman')
  t.agregarNodo(new Producto('limon', '8'), 'Tecun Uman')
  t.agregarNodo(new Producto('manzana', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('naranja', '12'), 'Tecun Uman')
  t.agregarNodo(new Producto('salchica', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('tocino', '20'), 'Tecun Uman')
  t.agregarNodo(new Producto('jamon', '5'), 'Tecun Uman')
  t.agregarNodo(new Producto('chorizo', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('suero', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('pasta dental', '10'), 'Tecun Uman')
  t.agregarNodo(new Producto('shampoo', '40'), 'Tecun Uman')
  t.agregarNodo(new Producto('servilletas', '5'), 'Tecun Uman')
  t.agregarNodo(new Producto('cloro', '20', 0), 'Tecun Uman')
  t.agregarNodo(new Producto('desinfectante', '15'), 'Tecun Uman')
  //productos San Marcos
  t.agregarNodo(new Producto('azucar', '5', '10'), 'San Marcos')
  t.agregarNodo(new Producto('leche', '12', '10'), 'San Marcos')
  t.agregarNodo(new Producto('papel', '12', '10'), 'San Marcos')
  t.agregarNodo(new Producto('aceite', '10', '10'), 'San Marcos')
  t.agregarNodo(new Producto('aderezos', '12', '10'), 'San Marcos')
  t.agregarNodo(new Producto('cafe', '5', '10'), 'San Marcos')
  t.agregarNodo(new Producto('avena', '7', '10'), 'San Marcos')
  t.agregarNodo(new Producto('cereales', '25', '10'), 'San Marcos')
  t.agregarNodo(new Producto('sal', '3', '10'), 'San Marcos')
  t.agregarNodo(new Producto('miel', '20', '10'), 'San Marcos')
  t.agregarNodo(new Producto('mayonesa', '15', '10'), 'San Marcos')
  t.agregarNodo(new Producto('mermelada', '12', '10'), 'San Marcos')
  t.agregarNodo(new Producto('te', '6', '10'), 'San Marcos')
  t.agregarNodo(new Producto('vinagre', '10', '10'), 'San Marcos')
  t.agregarNodo(new Producto('huevos', '25', '10'), 'San Marcos')
  t.agregarNodo(new Producto('pastas', '3', '10'), 'San Marcos')
  t.agregarNodo(new Producto('aceitunas', '8', '10'), 'San Marcos')
  t.agregarNodo(new Producto('champinones', '10', '10'), 'San Marcos')
  t.agregarNodo(new Producto('frijoles', '9', '10'), 'San Marcos')
  t.agregarNodo(new Producto('sardina', '7', '10'), 'San Marcos')
  t.agregarNodo(new Producto('atun', '15'), 'San Marcos')
  t.agregarNodo(new Producto('chile enlatado', '5', '10'), 'San Marcos')
  t.agregarNodo(new Producto('ensalada enlatada', '20', '10'), 'San Marcos')
  t.agregarNodo(new Producto('elote enlatado', '12', '10'), 'San Marcos')
  t.agregarNodo(new Producto('sopa enlatada', '5'), 'San Marcos')
  t.agregarNodo(new Producto('fruta enlatada', '25'), 'San Marcos')
  t.agregarNodo(new Producto('crema', '10'), 'San Marcos')
  t.agregarNodo(new Producto('margarina', '7'), 'San Marcos')
  t.agregarNodo(new Producto('queso', '20'), 'San Marcos')
  t.agregarNodo(new Producto('papa', '5'), 'San Marcos')
  t.agregarNodo(new Producto('cacahuates', '10'), 'San Marcos')
  t.agregarNodo(new Producto('nueces', '15'), 'San Marcos')
  t.agregarNodo(new Producto('tortilla de harina', '20', '10'), 'San Marcos')
  t.agregarNodo(new Producto('pan dulce', '2'), 'San Marcos')
  t.agregarNodo(new Producto('aguacate', '3'), 'San Marcos')
  t.agregarNodo(new Producto('ajo', '4'), 'San Marcos')
  t.agregarNodo(new Producto('cebolla', '6'), 'San Marcos')
  t.agregarNodo(new Producto('cilantro', '2'), 'San Marcos')
  t.agregarNodo(new Producto('tomate', '4'), 'San Marcos')
  t.agregarNodo(new Producto('limon', '8'), 'San Marcos')
  t.agregarNodo(new Producto('manzana', '10'), 'San Marcos')
  t.agregarNodo(new Producto('naranja', '12'), 'San Marcos')
  t.agregarNodo(new Producto('salchica', '10'), 'San Marcos')
  t.agregarNodo(new Producto('tocino', '20'), 'San Marcos')
  t.agregarNodo(new Producto('jamon', '5'), 'San Marcos')
  t.agregarNodo(new Producto('chorizo', '10'), 'San Marcos')
  t.agregarNodo(new Producto('suero', '10'), 'San Marcos')
  t.agregarNodo(new Producto('pasta dental', '10'), 'San Marcos')
  t.agregarNodo(new Producto('shampoo', '40'), 'San Marcos')
  t.agregarNodo(new Producto('servilletas', '5'), 'San Marcos')
  t.agregarNodo(new Producto('cloro', '20', 0), 'San Marcos')
  t.agregarNodo(new Producto('desinfectante', '15'), 'San Marcos')
  //productos San Rafael
  t.agregarNodo(new Producto('azucar', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('leche', '12', 15), 'San Rafael')
  t.agregarNodo(new Producto('papel', '12', 15), 'San Rafael')
  t.agregarNodo(new Producto('aceite', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('aderezos', '12', 15), 'San Rafael')
  t.agregarNodo(new Producto('cafe', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('avena', '7', 15), 'San Rafael')
  t.agregarNodo(new Producto('cereales', '25', 15), 'San Rafael')
  t.agregarNodo(new Producto('sal', '3', 15), 'San Rafael')
  t.agregarNodo(new Producto('miel', '20', 15), 'San Rafael')
  t.agregarNodo(new Producto('mayonesa', '15', 15), 'San Rafael')
  t.agregarNodo(new Producto('mermelada', '12', 15), 'San Rafael')
  t.agregarNodo(new Producto('te', '6', 15), 'San Rafael')
  t.agregarNodo(new Producto('vinagre', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('huevos', '25', 15), 'San Rafael')
  t.agregarNodo(new Producto('pastas', '3', 15), 'San Rafael')
  t.agregarNodo(new Producto('aceitunas', '8', 15), 'San Rafael')
  t.agregarNodo(new Producto('champinones', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('frijoles', '9', 15), 'San Rafael')
  t.agregarNodo(new Producto('sardina', '7', 15), 'San Rafael')
  t.agregarNodo(new Producto('atun', '15', 15), 'San Rafael')
  t.agregarNodo(new Producto('chile enlatado', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('ensalada enlatada', '20', 15), 'San Rafael')
  t.agregarNodo(new Producto('elote enlatado', '12', 15), 'San Rafael')
  t.agregarNodo(new Producto('sopa enlatada', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('fruta enlatada', '25', 15), 'San Rafael')
  t.agregarNodo(new Producto('crema', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('margarina', '7', 15), 'San Rafael')
  t.agregarNodo(new Producto('queso', '20', 15), 'San Rafael')
  t.agregarNodo(new Producto('papa', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('cacahuates', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('nueces', '15', 15), 'San Rafael')
  t.agregarNodo(new Producto('tortilla de harina', '20', 15), 'San Rafael')
  t.agregarNodo(new Producto('pan dulce', '2', 15), 'San Rafael')
  t.agregarNodo(new Producto('aguacate', '3', 15), 'San Rafael')
  t.agregarNodo(new Producto('ajo', '4', 15), 'San Rafael')
  t.agregarNodo(new Producto('cebolla', '6', 15), 'San Rafael')
  t.agregarNodo(new Producto('cilantro', '2', 15), 'San Rafael')
  t.agregarNodo(new Producto('tomate', '4', 15), 'San Rafael')
  t.agregarNodo(new Producto('limon', '8', 15), 'San Rafael')
  t.agregarNodo(new Producto('manzana', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('naranja', '12', 15), 'San Rafael')
  t.agregarNodo(new Producto('salchica', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('tocino', '20', 15), 'San Rafael')
  t.agregarNodo(new Producto('jamon', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('chorizo', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('suero', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('pasta dental', '10', 15), 'San Rafael')
  t.agregarNodo(new Producto('shampoo', '40', 15), 'San Rafael')
  t.agregarNodo(new Producto('servilletas', '5', 15), 'San Rafael')
  t.agregarNodo(new Producto('cloro', '20', 15), 'San Rafael')
  t.agregarNodo(new Producto('desinfectante', '15', 15), 'San Rafael')
  return t
}

let data = gData()
export default data
